// <auto-generated />
using System;
using GarbageCollectionApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarbageCollectionApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250325202953_CreateAdminTable")]
    partial class CreateAdminTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("GarbageCollectionApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBin", b =>
                {
                    b.Property<string>("IdGarbageBin")
                        .HasColumnType("TEXT");

                    b.HasKey("IdGarbageBin");

                    b.ToTable("GarbageBins");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBinCitizen", b =>
                {
                    b.Property<string>("IdGarbageBin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCitizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdGarbageBin", "IdCitizen");

                    b.HasIndex("IdCitizen");

                    b.ToTable("GarbageBinCitizens");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdGarbageBin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GarbageCollections");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBinCitizen", b =>
                {
                    b.HasOne("GarbageCollectionApp.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("IdCitizen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarbageCollectionApp.Models.GarbageBin", "GarbageBin")
                        .WithMany()
                        .HasForeignKey("IdGarbageBin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("GarbageBin");
                });
#pragma warning restore 612, 618
        }
    }
}
