// <auto-generated />
using System;
using GarbageCollectionApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarbageCollectionApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("GarbageCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdGarbageBin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdGarbageBin");

                    b.ToTable("GarbageCollections");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBin", b =>
                {
                    b.Property<string>("IdGarbageBin")
                        .HasColumnType("TEXT");

                    b.HasKey("IdGarbageBin");

                    b.ToTable("GarbageBins");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBinCitizen", b =>
                {
                    b.Property<string>("IdGarbageBin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCitizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdGarbageBin", "IdCitizen");

                    b.HasIndex("IdCitizen");

                    b.ToTable("GarbageBinCitizens");
                });

            modelBuilder.Entity("GarbageCollection", b =>
                {
                    b.HasOne("GarbageCollectionApp.Models.GarbageBin", "GarbageBin")
                        .WithMany("GarbageCollections")
                        .HasForeignKey("IdGarbageBin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GarbageBin");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBinCitizen", b =>
                {
                    b.HasOne("GarbageCollectionApp.Models.Citizen", "Citizen")
                        .WithMany("GarbageBinCitizens")
                        .HasForeignKey("IdCitizen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarbageCollectionApp.Models.GarbageBin", "GarbageBin")
                        .WithMany("GarbageBinCitizens")
                        .HasForeignKey("IdGarbageBin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("GarbageBin");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.Citizen", b =>
                {
                    b.Navigation("GarbageBinCitizens");
                });

            modelBuilder.Entity("GarbageCollectionApp.Models.GarbageBin", b =>
                {
                    b.Navigation("GarbageBinCitizens");

                    b.Navigation("GarbageCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
